# This file defines the configuration for Netlify.

# The `functions` section controls whether or not functions are enabled for the site.
[functions]

  # The `render` section specifies the configuration for the Render functions.
  [functions.render]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

# The `render` property specifies the URL of the Render endpoint.
render = "https://trisocialapp.onrender.com"